/**
 * 75th QUARTER QUELL // TRIBUTES & CLOCK ARENA DATA
 * Authentic tributes and 12-hour clock arena sector trap specifications.
 */

// 12-Hour Clock Sectors Specification (Quarter Quell Clock Arena)
const CLOCK_SECTORS = [
  {
    hour: 12,
    hourLabel: "12–1 o'clock",
    name: 'Lightning Tree',
    icon: '⚡',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'EXTREME (LETHAL)',
    summary: 'Massive towering banyan tree hit by lightning precisely at the stroke of 12:00. Millions of volts discharge through tree and conductor wire, vaporizing anyone nearby.',
    environment: 'Ancient Giant Banyan, deep mossy roots, high-voltage static charge',
    trapType: 'lightning',
    angleStart: (11 * Math.PI) / 6,
    angleEnd: 0, // 12 o'clock top
    midAngle: -Math.PI / 12,
    cameraOffset: { x: 0, y: 35, z: 45 },
    target: { x: 0, y: 5, z: -38 }
  },
  {
    hour: 1,
    hourLabel: "1–2 o'clock",
    name: 'Blood Rain',
    icon: '🩸',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'HIGH (CHOKING)',
    summary: 'Heavy, torrential downpour of warm, thick blood saturates the jungle canopy. Blinds vision, chokes respiratory passages, and causes severe psychological distress.',
    environment: 'Dense mangrove, crimson waterfalls, blood-soaked foliage',
    trapType: 'blood_rain',
    angleStart: 0,
    angleEnd: Math.PI / 6,
    midAngle: Math.PI / 12,
    cameraOffset: { x: 25, y: 35, z: 40 },
    target: { x: 20, y: 5, z: -32 }
  },
  {
    hour: 2,
    hourLabel: "2–3 o'clock",
    name: 'Poisonous Fog',
    icon: '🌫️',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'CRITICAL (PARALYZING)',
    summary: 'Dense synthetic nerve-toxin mist creeping steadily through the trees. Causes immediate agonizing chemical blisters, nerve spasms, and rapid respiratory failure unless cleansed by saltwater.',
    environment: 'Mist-shrouded jungle floor, corroded undergrowth, burning scent',
    trapType: 'poison_fog',
    angleStart: Math.PI / 6,
    angleEnd: Math.PI / 3,
    midAngle: Math.PI / 4,
    cameraOffset: { x: 42, y: 35, z: 25 },
    target: { x: 32, y: 5, z: -18 }
  },
  {
    hour: 3,
    hourLabel: "3–4 o'clock",
    name: 'Monkey Muttations',
    icon: '🐒',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'EXTREME (SWARM)',
    summary: 'Carnivorous engineered baboon muttations dormant in the canopy. When provoked or on schedule, hundreds descend with razor-sharp fangs and coordinated pack assault.',
    environment: 'Lush fruit canopies, hanging vines, echoing predator chirps',
    trapType: 'monkeys',
    angleStart: Math.PI / 3,
    angleEnd: Math.PI / 2,
    midAngle: (5 * Math.PI) / 12,
    cameraOffset: { x: 48, y: 35, z: 0 },
    target: { x: 38, y: 5, z: 0 }
  },
  {
    hour: 4,
    hourLabel: "4–5 o'clock",
    name: 'Jabberjays',
    icon: '🐦',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'CRITICAL (PSYCHOLOGICAL)',
    summary: 'Traps tributes behind an impassable invisible forcefield. Flocks of black crested birds broadcast looped, agonizing screams of tributes’ loved ones, driving victims to insanity.',
    environment: 'Gilded bamboo thicket, forcefield threshold, acoustic amplification basin',
    trapType: 'jabberjays',
    angleStart: Math.PI / 2,
    angleEnd: (2 * Math.PI) / 3,
    midAngle: (7 * Math.PI) / 12,
    cameraOffset: { x: 42, y: 35, z: -25 },
    target: { x: 32, y: 5, z: 18 }
  },
  {
    hour: 5,
    hourLabel: "5–6 o'clock",
    name: 'Total Darkness',
    icon: '🌑',
    isFanTheory: true,
    canonStatus: 'UNCONFIRMED / FAN THEORY',
    dangerLevel: 'HIGH (DISORIENTING)',
    summary: 'Complete sensor and photon blackout. Absolute darkness descends on the sector, blinding tribute vision and infrared surveillance cameras, masking silent ambushers.',
    environment: 'Pitch-black obsidian grove, light-absorbing atmospheric particulate',
    trapType: 'darkness',
    angleStart: (2 * Math.PI) / 3,
    angleEnd: (5 * Math.PI) / 6,
    midAngle: (9 * Math.PI) / 12,
    cameraOffset: { x: 25, y: 35, z: -40 },
    target: { x: 20, y: 5, z: 32 }
  },
  {
    hour: 6,
    hourLabel: "6–7 o'clock",
    name: 'Mysterious Beast',
    icon: '👹',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'LETHAL (APEX CARNIVORE)',
    summary: 'A colossal subterranean predator lurking beneath the damp earth. Drags unlucky tributes into its burrow and tears them to shreds before receding below.',
    environment: 'Gouged trenches, uprooted tree trunks, echoing guttural growls',
    trapType: 'beast',
    angleStart: (5 * Math.PI) / 6,
    angleEnd: Math.PI,
    midAngle: (11 * Math.PI) / 12,
    cameraOffset: { x: 0, y: 35, z: -48 },
    target: { x: 0, y: 5, z: 38 }
  },
  {
    hour: 7,
    hourLabel: "7–8 o'clock",
    name: 'Quicksand',
    icon: '⏳',
    isFanTheory: true,
    canonStatus: 'UNCONFIRMED / FAN THEORY',
    dangerLevel: 'HIGH (ENVIRONMENTAL)',
    summary: 'The forest floor liquefies into deceptive, bottomless silt. Struggling accelerates sinking, suffocating tributes beneath tons of shifting mud.',
    environment: 'Deceptive mossy glades, bubbling mud sinkholes, collapsing ground',
    trapType: 'quicksand',
    angleStart: Math.PI,
    angleEnd: (7 * Math.PI) / 6,
    midAngle: (13 * Math.PI) / 12,
    cameraOffset: { x: -25, y: 35, z: -40 },
    target: { x: -20, y: 5, z: 32 }
  },
  {
    hour: 8,
    hourLabel: "8–9 o'clock",
    name: 'Swarming Mutt Spiders',
    icon: '🕷️',
    isFanTheory: true,
    canonStatus: 'UNCONFIRMED / FAN THEORY',
    dangerLevel: 'EXTREME (SWARM)',
    summary: 'Gigantic, chitinous arachnid muttations erupt from underground burrows and webs, injecting flesh-liquefying neurotoxins.',
    environment: 'Heavy silk webbing, skeletal hollows, multi-eyed skittering',
    trapType: 'spiders',
    angleStart: (7 * Math.PI) / 6,
    angleEnd: (4 * Math.PI) / 3,
    midAngle: (15 * Math.PI) / 12,
    cameraOffset: { x: -42, y: 35, z: -25 },
    target: { x: -32, y: 5, z: 18 }
  },
  {
    hour: 9,
    hourLabel: "9–10 o'clock",
    name: 'Dangerous Vines',
    icon: '🌿',
    isFanTheory: true,
    canonStatus: 'UNCONFIRMED / FAN THEORY',
    dangerLevel: 'HIGH (CONSTRICTING)',
    summary: 'Carnivorous, prehensile jungle vines that react to warmth and motion. Whip around limbs and constrict victims with barbed thorns.',
    environment: 'Thorny brambles, pulsating thick creepers, choking canopy',
    trapType: 'vines',
    angleStart: (4 * Math.PI) / 3,
    angleEnd: (3 * Math.PI) / 2,
    midAngle: (17 * Math.PI) / 12,
    cameraOffset: { x: -48, y: 35, z: 0 },
    target: { x: -38, y: 5, z: 0 }
  },
  {
    hour: 10,
    hourLabel: "10–11 o'clock",
    name: 'Giant Wave',
    icon: '🌊',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'CATASTROPHIC (DELUGE)',
    summary: 'A towering, 80-foot saltwater wall of water crashes inward from the sector perimeter at immense velocity, sweeping all tributes and debris out onto the central beach.',
    environment: 'Flooded sea channels, crushed timber, receding whitewater surf',
    trapType: 'wave',
    angleStart: (3 * Math.PI) / 2,
    angleEnd: (5 * Math.PI) / 3,
    midAngle: (19 * Math.PI) / 12,
    cameraOffset: { x: -42, y: 35, z: 25 },
    target: { x: -32, y: 5, z: -18 }
  },
  {
    hour: 11,
    hourLabel: "11–12 o'clock",
    name: 'Deadly Insects',
    icon: '🦗',
    isFanTheory: false,
    canonStatus: 'CANONICAL',
    dangerLevel: 'EXTREME (AGGRESSIVE)',
    summary: 'A deafening, high-pitched mechanical buzzing precedes millions of carnivorous beetles and stinging wasps devouring all flesh in seconds.',
    environment: 'Hollow boles, buzzing air currents, stripped bark',
    trapType: 'insects',
    angleStart: (5 * Math.PI) / 3,
    angleEnd: (11 * Math.PI) / 6,
    midAngle: (21 * Math.PI) / 12,
    cameraOffset: { x: -25, y: 35, z: 40 },
    target: { x: -20, y: 5, z: -32 }
  }
];

// 24 Canonical Tributes for the 75th Quarter Quell
const INITIAL_TRIBUTES = [
  // District 1 (Luxury)
  {
    id: 'd1-m',
    name: 'Gloss',
    district: 1,
    districtName: 'Luxury',
    gender: 'M',
    avatar: '💎',
    image: 'assets/images/gloss.png',
    isCareer: true,
    maxHealth: 100,
    health: 100,
    strength: 88,
    stealth: 55,
    stamina: 85,
    inventory: ['Throwing Daggers', 'Golden Blade'],
    kills: 0,
    status: 'alive',
    sector: 1,
    coordinates: { x: 7, y: -22 },
    odds: '12.50'
  },
  {
    id: 'd1-f',
    name: 'Cashmere',
    district: 1,
    districtName: 'Luxury',
    gender: 'F',
    avatar: '✨',
    image: 'assets/images/cashmere.png',
    isCareer: true,
    maxHealth: 100,
    health: 100,
    strength: 84,
    stealth: 60,
    stamina: 82,
    inventory: ['Curved Sickle', 'Armor Plating'],
    kills: 0,
    status: 'alive',
    sector: 1,
    coordinates: { x: 12, y: -24 },
    odds: '15.00'
  },

  // District 2 (Masonry)
  {
    id: 'd2-m',
    name: 'Brutus',
    district: 2,
    districtName: 'Masonry',
    gender: 'M',
    avatar: '⚔️',
    isCareer: true,
    maxHealth: 100,
    health: 100,
    strength: 96,
    stealth: 35,
    stamina: 92,
    inventory: ['Spear', 'Iron Breastplate'],
    kills: 0,
    status: 'alive',
    sector: 2,
    coordinates: { x: 22, y: -12 },
    odds: '8.50'
  },
  {
    id: 'd2-f',
    name: 'Enobaria',
    district: 2,
    districtName: 'Masonry',
    gender: 'F',
    avatar: '🗡️',
    image: 'assets/images/enobaria.png',
    isCareer: true,
    maxHealth: 100,
    health: 100,
    strength: 92,
    stealth: 50,
    stamina: 90,
    inventory: ['Gold-Inlaid Teeth', 'Short Sword'],
    kills: 0,
    status: 'alive',
    sector: 2,
    coordinates: { x: 24, y: -7 },
    odds: '10.00'
  },

  // District 3 (Technology)
  {
    id: 'd3-m',
    name: 'Beetee',
    district: 3,
    districtName: 'Technology',
    gender: 'M',
    avatar: '⚡',
    image: 'assets/images/beetee.png',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 42,
    stealth: 82,
    stamina: 60,
    inventory: ['Gold Conductor Wire', 'Detonator Relay'],
    kills: 0,
    status: 'alive',
    sector: 12, // Near Lightning Tree
    coordinates: { x: 3, y: -26 },
    odds: '22.00'
  },
  {
    id: 'd3-f',
    name: 'Wiress',
    district: 3,
    districtName: 'Technology',
    gender: 'F',
    avatar: '💡',
    image: 'assets/images/wiress.png',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 40,
    stealth: 80,
    stamina: 55,
    inventory: ['Electrum Wire', 'Small Dirk'],
    kills: 0,
    status: 'alive',
    sector: 12,
    coordinates: { x: -3, y: -25 },
    odds: '35.00'
  },

  // District 4 (Fishing)
  {
    id: 'd4-m',
    name: 'Finnick Odair',
    district: 4,
    districtName: 'Fishing',
    gender: 'M',
    avatar: '🔱',
    isCareer: true,
    maxHealth: 100,
    health: 100,
    strength: 92,
    stealth: 80,
    stamina: 90,
    inventory: ['Trident of the Sea', 'Weighted Wire Net'],
    kills: 0,
    status: 'alive',
    sector: 4,
    coordinates: { x: 24, y: 12 },
    odds: '5.20'
  },
  {
    id: 'd4-f',
    name: 'Mags Flanagan',
    district: 4,
    districtName: 'Fishing',
    gender: 'F',
    avatar: '🌊',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 35,
    stealth: 85,
    stamina: 50,
    inventory: ['Woven Fishhook', 'Medicinal Moss'],
    kills: 0,
    status: 'alive',
    sector: 4,
    coordinates: { x: 22, y: 7 },
    odds: '65.00'
  },

  // District 5 (Power)
  {
    id: 'd5-m',
    name: 'Felix',
    district: 5,
    districtName: 'Power',
    gender: 'M',
    avatar: '🔋',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 58,
    stealth: 65,
    stamina: 70,
    inventory: ['Insulated Gloves', 'Flashlight'],
    kills: 0,
    status: 'alive',
    sector: 5,
    coordinates: { x: 14, y: 22 },
    odds: '40.00'
  },
  {
    id: 'd5-f',
    name: 'Ivory',
    district: 5,
    districtName: 'Power',
    gender: 'F',
    avatar: '⚡',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 52,
    stealth: 72,
    stamina: 68,
    inventory: ['Circuit Spike', 'Bandages'],
    kills: 0,
    status: 'alive',
    sector: 5,
    coordinates: { x: 8, y: 24 },
    odds: '45.00'
  },

  // District 6 (Transportation)
  {
    id: 'd6-m',
    name: 'Morphling M',
    district: 6,
    districtName: 'Transportation',
    gender: 'M',
    avatar: '🎨',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 45,
    stealth: 94,
    stamina: 58,
    inventory: ['Camouflage Body Paint'],
    kills: 0,
    status: 'alive',
    sector: 6,
    coordinates: { x: 3, y: 25 },
    odds: '50.00'
  },
  {
    id: 'd6-f',
    name: 'Morphling F',
    district: 6,
    districtName: 'Transportation',
    gender: 'F',
    avatar: '🖌️',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 42,
    stealth: 95,
    stamina: 56,
    inventory: ['Camouflage Clay', 'Small Blade'],
    kills: 0,
    status: 'alive',
    sector: 6,
    coordinates: { x: -3, y: 25 },
    odds: '55.00'
  },

  // District 7 (Lumber)
  {
    id: 'd7-m',
    name: 'Blight',
    district: 7,
    districtName: 'Lumber',
    gender: 'M',
    avatar: '🪵',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 78,
    stealth: 60,
    stamina: 78,
    inventory: ['Woodcutter Axe'],
    kills: 0,
    status: 'alive',
    sector: 7,
    coordinates: { x: -14, y: 22 },
    odds: '30.00'
  },
  {
    id: 'd7-f',
    name: 'Johanna Mason',
    district: 7,
    districtName: 'Lumber',
    gender: 'F',
    avatar: '🪓',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 88,
    stealth: 88,
    stamina: 88,
    inventory: ['Pair of Combat Axes', 'Spool of Wire'],
    kills: 0,
    status: 'alive',
    sector: 7,
    coordinates: { x: -20, y: 16 },
    odds: '7.80'
  },

  // District 8 (Textiles)
  {
    id: 'd8-m',
    name: 'Woof',
    district: 8,
    districtName: 'Textiles',
    gender: 'M',
    avatar: '🧶',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 40,
    stealth: 62,
    stamina: 50,
    inventory: ['Heavy Shears', 'Thermal Cloth'],
    kills: 0,
    status: 'alive',
    sector: 8,
    coordinates: { x: -24, y: 10 },
    odds: '70.00'
  },
  {
    id: 'd8-f',
    name: 'Cecelia',
    district: 8,
    districtName: 'Textiles',
    gender: 'F',
    avatar: '🧵',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 52,
    stealth: 70,
    stamina: 66,
    inventory: ['Sewing Needles Blade', 'Waterskin'],
    kills: 0,
    status: 'alive',
    sector: 8,
    coordinates: { x: -25, y: 4 },
    odds: '48.00'
  },

  // District 9 (Grain)
  {
    id: 'd9-m',
    name: 'Daniel',
    district: 9,
    districtName: 'Grain',
    gender: 'M',
    avatar: '🌾',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 65,
    stealth: 58,
    stamina: 74,
    inventory: ['Grain Scythe'],
    kills: 0,
    status: 'alive',
    sector: 9,
    coordinates: { x: -25, y: -6 },
    odds: '38.00'
  },
  {
    id: 'd9-f',
    name: 'Leona',
    district: 9,
    districtName: 'Grain',
    gender: 'F',
    avatar: '🌻',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 58,
    stealth: 66,
    stamina: 72,
    inventory: ['Sickle Knife', 'Seeds Flask'],
    kills: 0,
    status: 'alive',
    sector: 9,
    coordinates: { x: -24, y: -12 },
    odds: '42.00'
  },

  // District 10 (Livestock)
  {
    id: 'd10-m',
    name: 'Tanner',
    district: 10,
    districtName: 'Livestock',
    gender: 'M',
    avatar: '🐂',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 72,
    stealth: 48,
    stamina: 80,
    inventory: ['Butcher Cleaver', 'Rope Lasso'],
    kills: 0,
    status: 'alive',
    sector: 10,
    coordinates: { x: -20, y: -18 },
    odds: '28.00'
  },
  {
    id: 'd10-f',
    name: 'Brandy',
    district: 10,
    districtName: 'Livestock',
    gender: 'F',
    avatar: '🐎',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 62,
    stealth: 64,
    stamina: 75,
    inventory: ['Skinning Knife', 'Leather Waterskin'],
    kills: 0,
    status: 'alive',
    sector: 10,
    coordinates: { x: -14, y: -22 },
    odds: '34.00'
  },

  // District 11 (Agriculture)
  {
    id: 'd11-m',
    name: 'Chaff',
    district: 11,
    districtName: 'Agriculture',
    gender: 'M',
    avatar: '🌾',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 86,
    stealth: 55,
    stamina: 88,
    inventory: ['Prosthetic Knife-Arm', 'Field Bread'],
    kills: 0,
    status: 'alive',
    sector: 11,
    coordinates: { x: -8, y: -24 },
    odds: '14.00'
  },
  {
    id: 'd11-f',
    name: 'Seeder',
    district: 11,
    districtName: 'Agriculture',
    gender: 'F',
    avatar: '🌱',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 64,
    stealth: 78,
    stamina: 82,
    inventory: ['Pruning Hook', 'Edible Plants Pouch'],
    kills: 0,
    status: 'alive',
    sector: 11,
    coordinates: { x: -3, y: -26 },
    odds: '25.00'
  },

  // District 12 (Mining)
  {
    id: 'd12-m',
    name: 'Peeta Mellark',
    district: 12,
    districtName: 'Mining',
    gender: 'M',
    avatar: '🎨',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 82,
    stealth: 88,
    stamina: 84,
    inventory: ['Camouflage Clay', 'Heavy Pearl', 'Combat Knife'],
    kills: 0,
    status: 'alive',
    sector: 12,
    coordinates: { x: 2, y: -16 },
    odds: '4.50'
  },
  {
    id: 'd12-f',
    name: 'Katniss Everdeen',
    district: 12,
    districtName: 'Mining',
    gender: 'F',
    avatar: '🏹',
    isCareer: false,
    maxHealth: 100,
    health: 100,
    strength: 90,
    stealth: 96,
    stamina: 94,
    inventory: ['Capitol Hunting Bow', 'Mockingjay Pin', 'Quiver of 24'],
    kills: 0,
    status: 'alive',
    sector: 12,
    coordinates: { x: 0, y: -18 },
    odds: '3.10'
  }
];
